<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your Email IDMobile Number_emai_a52cda</name>
   <tag></tag>
   <elementGuidId>d5574a3e-82fa-493b-8fdf-7e74dfa4ec5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailOrPhoneField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailOrPhoneField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab29a761-ac28-49a3-92ba-dee4ff781367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailOrPhoneField</value>
      <webElementGuid>cfc836ef-3842-4794-8337-76675ac60d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>73951cfa-5ae1-4c36-b395-134031feeba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>0681f143-65e0-4fb1-a3ff-4bd3c73591fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input !p-3 leading-[22px] text-sm text-textBaseDarkLight dark:text-textBaseDarkDark font-bold bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark css-zj9fva ant-input-outlined rounded-md placeholder:text-textBaseGraymediumLight dark:placeholder:text-textBaseGraymediumDark placeholder:font-normal bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark [&amp;_.ant-input-group-addon]:!overflow-hidden [&amp;_.ant-input-group-addon]:!bg-surfaceBaseWhiteLight [&amp;_.ant-input-group-addon]:dark:!bg-surfaceBaseWhiteDark disabled:bg-surfaceBaseGreylightLight dark:disabled:bg-surfaceBaseGreylightDark  mt-2 h-12 !font-normal disabled:bg-transparent dark:disabled:bg-transparent  [&amp;_.ant-input-group-addon]:px-2 [&amp;_.ant-input-group-addon]:py-2 [&amp;_.ant-input-disabled]:bg-surfaceBaseGreylightLight dark:[&amp;_.ant-input-disabled]:bg-surfaceBaseGreylightDark [&amp;_.ant-select-disabled]:bg-surfaceBaseGreylightLight dark:[&amp;_.ant-select-disabled]:bg-surfaceBaseGreylightDark 
          [&amp;_.ant-input-group-wrapper-disabled&amp;_.ant-input-group-addon]:!bg-surfaceBaseGreylightLight dark:[.ant-input-group-wrapper-disabled&amp;_.ant-input-group-addon]:!bg-surfaceBaseGreylightDark </value>
      <webElementGuid>ec7b2533-f002-47be-beb0-62274334cd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b963bf9-7757-4b89-be69-30e4baefc870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailOrPhoneField&quot;)</value>
      <webElementGuid>e6483636-3c61-4840-bcba-9122e86597a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailOrPhoneField']</value>
      <webElementGuid>c376d2a4-dcb2-464f-9d88-0e3f45fed448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='tailwind-core']/body/div[3]/main/section/section/form/section/input</value>
      <webElementGuid>ab523906-8372-4486-8416-63f937e92306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e4e595a8-20ad-4e25-bba3-ec9ebeee1df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emailOrPhoneField' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>bad52a43-c95c-402e-887a-245e6b7bf095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
