<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_India</name>
   <tag></tag>
   <elementGuidId>bed99cbc-7fe6-4362-86ac-b18e8de0ec7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>#rc_select_1_list</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ant-select-item-option-content div.justify-start.items-center.flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;India India&quot;i] >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f78e1e2-b41e-4629-ab5e-f828fac5684f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-start items-center gap-2 py-1</value>
      <webElementGuid>16553865-5952-49d2-be29-e2caad1264f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India</value>
      <webElementGuid>4b06ea9e-fa8b-4ad7-9262-5fdc871e8dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>India</value>
      <webElementGuid>20a0d74e-a42a-481e-ae20-cf4a72ec6d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0ffb980be9e2f9462a9d2e361752833e</value>
      <webElementGuid>5ca4d5a2-3d83-43f4-bdb3-e2abc61cc670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-item-option-content ')]//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-start ') and contains(concat(' ', normalize-space(@class), ' '), ' items-center ') and contains(concat(' ', normalize-space(@class), ' '), ' flex ')]</value>
      <webElementGuid>a4c46e85-af8e-42be-b80c-449b390f4de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-item-option-content ')]//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-start ') and contains(concat(' ', normalize-space(@class), ' '), ' items-center ') and contains(concat(' ', normalize-space(@class), ' '), ' flex ')]</value>
      <webElementGuid>3e78b011-0605-482e-9748-0bd179fc8dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'India' or . = 'India')]</value>
      <webElementGuid>2182bfea-579c-4215-821d-e07898ca5d20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
