<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_USD  ENG_text-iconWhiteLight</name>
   <tag></tag>
   <elementGuidId>37df55b7-c5c6-4761-979f-ff13abdc7dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-5.h-5.flex.justify-center.items-center > svg.text-iconWhiteLight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='USD / ENG'])[1]/following::*[name()='svg'][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Main navigation&quot;i >> svg >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4a10a842-977c-4f2c-b407-a9fc591b97e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-iconWhiteLight</value>
      <webElementGuid>05f068fd-a82c-45c3-acc7-0aa6f8187ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>65041c24-0e7c-424a-b42e-28c555fba60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f4c99e1-28bd-49af-b1a2-49b8f44ee3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>26da7bc3-aee2-4597-9c05-db242a0616c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
      <webElementGuid>8cdb61c2-c26a-4817-9d6c-189786643c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>e3300ec5-8eb4-4aa3-9228-34142d024c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>232bc6c4-0485-4de9-a4be-3690082cb9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>f33df7e4-0f24-4c79-982c-0aaa35f59065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-user&quot;)/div[@class=&quot;w-5 h-5 flex justify-center items-center&quot;]/svg[@class=&quot;text-iconWhiteLight&quot;]</value>
      <webElementGuid>1a038d0b-7bb1-4248-a445-016d405cf266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD / ENG'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>9c4efc4c-de58-49b7-b94b-6e57eee87b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>2ebf41b4-a32c-4803-b250-8f180a93fde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel the World'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>89a1167f-c6fc-48ff-bd06-f9b798769e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='one adventure at a time'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>1bf2f1fa-fd0e-4f31-aa3a-506c90223a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
